// docs-index.ts — the shipped documentation, loaded from disk and searched
// lexically. Backs the `nodal_docs` built-in tool.
//
// WHY LEXICAL, OFFLINE, NO MODEL. The agent asking "where do I set up a
// Telegram bot?" is already inside an LLM turn; spending a second model call —
// or an embedding index that has to be built, stored and kept in sync — to
// find a page buys nothing a keyword match cannot. It also means this works on
// an install with no network and no API budget left, which is exactly the
// moment someone needs the documentation. Deterministic scoring keeps the
// tests honest: the same question always returns the same sections.
//
// The index itself is DERIVED from apps/docs/content/docs by
// apps/docs/scripts/gen-docs-index.ts. Nothing about the platform is written
// twice.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface DocsSection {
  page: string;
  pageTitle: string;
  heading: string;
  url: string;
  text: string;
}

export interface DocsIndex {
  generator: string;
  sections: DocsSection[];
}

// ─── Loading ──────────────────────────────────────────────────────────────────

/** Thrown when the index is missing or unreadable. Loud, never a silent empty. */
export class DocsIndexUnavailableError extends Error {
  constructor(probed: string[], cause?: unknown) {
    super(
      `nodal_docs: the documentation index was not found. Probed: ${probed.join(', ')}. ` +
        `It is generated by apps/docs/scripts/gen-docs-index.ts (run \`pnpm build\`) and ` +
        `shipped in the package next to migrations/.` +
        (cause instanceof Error ? ` Cause: ${cause.message}` : ''),
    );
    this.name = 'DocsIndexUnavailableError';
  }
}

/**
 * Where the index can be, in probe order — the same two layouts
 * `packages/db/src/migrate.ts` handles for `migrations/`:
 *   - bundled pack: this module is inlined into runner.js at the pack root, so
 *     the index is a SIBLING (`pack/docs-index.json`);
 *   - monorepo dev: this file is packages/tools/src/builtin/docs-index.ts, so
 *     the index is two levels up (`packages/tools/docs-index.json`).
 * Sibling first: cheaper, and the common case in a shipped artifact.
 */
export function docsIndexCandidatePaths(here: string): string[] {
  return [join(here, 'docs-index.json'), join(here, '..', '..', 'docs-index.json')];
}

let cached: DocsIndex | null = null;

/**
 * Read the index, once per process. Cached because it is a few hundred kB of
 * immutable data read on a tool call inside an LLM turn.
 */
export function loadDocsIndex(): DocsIndex {
  if (cached !== null) return cached;
  const here = dirname(fileURLToPath(import.meta.url));
  const probed = docsIndexCandidatePaths(here);
  const found = probed.find((p) => existsSync(p));
  if (found === undefined) throw new DocsIndexUnavailableError(probed);
  try {
    const parsed = JSON.parse(readFileSync(found, 'utf8')) as DocsIndex;
    if (!Array.isArray(parsed.sections)) throw new Error('no `sections` array');
    cached = parsed;
    return parsed;
  } catch (err) {
    throw new DocsIndexUnavailableError([found], err);
  }
}

/** Test seam: drop the cached index so a test can load a fixture. */
export function resetDocsIndexCache(): void {
  cached = null;
}

// ─── Scoring ──────────────────────────────────────────────────────────────────

/**
 * Words carried by every question, which would otherwise match every section
 * and flatten the ranking. Deliberately short: anything domain-bearing stays,
 * including "set" and "up", because "set up" IS the heading people are looking
 * for.
 */
const STOPWORDS = new Set([
  'a',
  'an',
  'and',
  'are',
  'as',
  'at',
  'be',
  'but',
  'by',
  'can',
  'do',
  'does',
  'for',
  'from',
  'how',
  'i',
  'if',
  'in',
  'is',
  'it',
  'me',
  'my',
  'of',
  'on',
  'or',
  'our',
  'so',
  'that',
  'the',
  'their',
  'them',
  'then',
  'there',
  'these',
  'they',
  'this',
  'to',
  'was',
  'we',
  'what',
  'when',
  'which',
  'who',
  'will',
  'with',
  'you',
  'your',
]);

/** Lowercase, accents removed, split on anything that is not a letter or digit. */
export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .split(/[^a-z0-9]+/)
    .filter((w) => w !== '');
}

/** The distinct, meaningful terms of a question, in first-seen order. */
export function queryTerms(question: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const word of normalizeWords(question)) {
    if (STOPWORDS.has(word)) continue;
    if (seen.has(word)) continue;
    seen.add(word);
    out.push(word);
  }
  return out;
}

/**
 * Does `term` occur in `words`? A term of four characters or more also matches
 * a word it prefixes, so "configure" finds "configured" and "automation" finds
 * "automations" without a stemmer and without matching "to" against "token".
 */
function occurrences(words: readonly string[], term: string): number {
  let n = 0;
  for (const word of words) {
    if (word === term || (term.length >= 4 && word.startsWith(term))) n += 1;
  }
  return n;
}

/**
 * Field weights. A heading is what the section is ABOUT, so it outranks the
 * page it lives on, which outranks a passing mention in the prose.
 */
const WEIGHT_HEADING = 6;
const WEIGHT_PAGE_TITLE = 4;
const WEIGHT_PAGE_PATH = 3;
const WEIGHT_BODY = 2;
/** Repeats count, but with sharply diminishing returns — never as a new field. */
const WEIGHT_BODY_REPEAT = 0.2;
const BODY_REPEAT_CAP = 1;
/**
 * Coverage — the share of the question's terms a section addresses at all —
 * SCALES the field score instead of being added to it.
 *
 * It used to be a bonus of at most 3 points, and Reviewer C showed that was no
 * rule at all: a heading match is worth 6, so on a two-word question a section
 * answering half of it in its heading beat a section answering all of it in its
 * prose, and the bonus only decided a band so narrow that the test pinning it
 * had to repeat a word six times to land inside it. Proportional, the rule is
 * the one the ranking wants: answering half the question is worth about half as
 * much, whichever field the half was found in.
 *
 * The floor keeps a partial match from collapsing: a long question about one
 * topic still points at that topic. With two terms, matching one scales to 0.6
 * rather than 0.5.
 */
const COVERAGE_FLOOR = 0.2;

export interface DocsHit extends DocsSection {
  score: number;
}

/**
 * A section's fields, split into words once.
 *
 * Built per INDEX, not per search: the words of a section never change, and an
 * agent asks the manual more than once in a job. Doing it inside the search
 * loop re-split every section's prose on every question (Reviewer C, pass 2,
 * P2-10) — the only part of the cost that grew with use.
 */
interface Indexed {
  section: DocsSection;
  heading: string[];
  pageTitle: string[];
  pagePath: string[];
  body: string[];
}

function indexSection(section: DocsSection): Indexed {
  return {
    section,
    heading: normalizeWords(section.heading),
    pageTitle: normalizeWords(section.pageTitle),
    pagePath: normalizeWords(section.page),
    body: normalizeWords(section.text),
  };
}

/**
 * The split words of an index, memoised on the index object itself.
 *
 * Keyed by identity rather than stored in a module variable so a test that
 * passes a literal index gets the same treatment as the shipped one, and two
 * different indexes never see each other's words. A WeakMap so a discarded
 * index is collected with its words.
 *
 * The contract that follows from keying on identity, and that Reviewer C asked
 * to see written down (pass 3, C1): an index is IMMUTABLE once searched.
 * Pushing a section onto `index.sections` after a first search does not
 * invalidate anything, and the second search answers out of the old
 * vocabulary. That is sound for the only index this ships with, which is read
 * once from a file that cannot change under a running process; a caller
 * building one by hand must pass a new object rather than edit the old one.
 */
const indexedCache = new WeakMap<DocsIndex, Indexed[]>();

function indexedSections(index: DocsIndex): Indexed[] {
  const hit = indexedCache.get(index);
  if (hit !== undefined) return hit;
  const built = index.sections.map(indexSection);
  indexedCache.set(index, built);
  return built;
}

function scoreSection(entry: Indexed, terms: readonly string[]): number {
  let score = 0;
  let matched = 0;
  for (const term of terms) {
    let hit = false;
    if (occurrences(entry.heading, term) > 0) {
      score += WEIGHT_HEADING;
      hit = true;
    }
    if (occurrences(entry.pageTitle, term) > 0) {
      score += WEIGHT_PAGE_TITLE;
      hit = true;
    }
    if (occurrences(entry.pagePath, term) > 0) {
      score += WEIGHT_PAGE_PATH;
      hit = true;
    }
    const inBody = occurrences(entry.body, term);
    if (inBody > 0) {
      score += WEIGHT_BODY + Math.min((inBody - 1) * WEIGHT_BODY_REPEAT, BODY_REPEAT_CAP);
      hit = true;
    }
    if (hit) matched += 1;
  }
  if (matched === 0) return 0;
  const coverage = matched / terms.length;
  return score * (COVERAGE_FLOOR + (1 - COVERAGE_FLOOR) * coverage);
}

/**
 * The best sections for a question, best first.
 *
 * `index` must be IMMUTABLE once passed here: its words are split once and
 * memoised against the object (see `indexedSections`).
 *
 * Ties break on the URL, so the result never depends on the order the index
 * happened to be written in. A question whose every word is a stopword, or
 * which matches nothing, returns an empty array — the caller says so rather
 * than inventing a page (invariant #4).
 */
export function searchDocs(index: DocsIndex, question: string, limit: number): DocsHit[] {
  const terms = queryTerms(question);
  if (terms.length === 0) return [];

  const scored: DocsHit[] = [];
  for (const entry of indexedSections(index)) {
    const score = scoreSection(entry, terms);
    if (score > 0) scored.push({ ...entry.section, score });
  }

  scored.sort((a, b) => (b.score !== a.score ? b.score - a.score : a.url.localeCompare(b.url)));
  return scored.slice(0, limit);
}
