// docs-index.ts — the shipped documentation, loaded from disk and searched
// lexically. Backs the `nodal_docs` built-in tool.
//
// WHY LEXICAL, OFFLINE, NO MODEL. The agent asking "where do I set up a
// Telegram bot?" is already inside an LLM turn; spending a second model call —
// or an embedding index that has to be built, stored and kept in sync — to
// find a page buys nothing a keyword match cannot. It also means this works on
// an install with no network and no API budget left, which is exactly the
// moment someone needs the documentation. Deterministic scoring keeps the
// tests honest: the same question always returns the same sections.
//
// The index itself is DERIVED from apps/docs/content/docs by
// apps/docs/scripts/gen-docs-index.ts. Nothing about the platform is written
// twice.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface DocsSection {
  page: string;
  pageTitle: string;
  heading: string;
  url: string;
  text: string;
  /** A section of the release notes (#452); see `nodalReleaseIntent`. */
  release?: boolean;
}

export interface DocsIndex {
  generator: string;
  sections: DocsSection[];
}

// ─── Loading ──────────────────────────────────────────────────────────────────

/** Thrown when the index is missing or unreadable. Loud, never a silent empty. */
export class DocsIndexUnavailableError extends Error {
  constructor(probed: string[], cause?: unknown) {
    super(
      `nodal_docs: the documentation index was not found. Probed: ${probed.join(', ')}. ` +
        `It is generated by apps/docs/scripts/gen-docs-index.ts (run \`pnpm build\`) and ` +
        `shipped in the package next to migrations/.` +
        (cause instanceof Error ? ` Cause: ${cause.message}` : ''),
    );
    this.name = 'DocsIndexUnavailableError';
  }
}

/**
 * Where the index can be, in probe order — the same two layouts
 * `packages/db/src/migrate.ts` handles for `migrations/`:
 *   - bundled pack: this module is inlined into runner.js at the pack root, so
 *     the index is a SIBLING (`pack/docs-index.json`);
 *   - monorepo dev: this file is packages/tools/src/builtin/docs-index.ts, so
 *     the index is two levels up (`packages/tools/docs-index.json`).
 * Sibling first: cheaper, and the common case in a shipped artifact.
 */
export function docsIndexCandidatePaths(here: string): string[] {
  return [join(here, 'docs-index.json'), join(here, '..', '..', 'docs-index.json')];
}

let cached: DocsIndex | null = null;

/**
 * Read the index, once per process. Cached because it is a few hundred kB of
 * immutable data read on a tool call inside an LLM turn.
 */
export function loadDocsIndex(): DocsIndex {
  if (cached !== null) return cached;
  const here = dirname(fileURLToPath(import.meta.url));
  const probed = docsIndexCandidatePaths(here);
  const found = probed.find((p) => existsSync(p));
  if (found === undefined) throw new DocsIndexUnavailableError(probed);
  try {
    const parsed = JSON.parse(readFileSync(found, 'utf8')) as DocsIndex;
    if (!Array.isArray(parsed.sections)) throw new Error('no `sections` array');
    cached = parsed;
    return parsed;
  } catch (err) {
    throw new DocsIndexUnavailableError([found], err);
  }
}

/** Test seam: drop the cached index so a test can load a fixture. */
export function resetDocsIndexCache(): void {
  cached = null;
}

// ─── Scoring ──────────────────────────────────────────────────────────────────

/**
 * Words carried by every question, which would otherwise match every section
 * and flatten the ranking. Deliberately short: anything domain-bearing stays,
 * including "set" and "up", because "set up" IS the heading people are looking
 * for.
 */
const STOPWORDS = new Set([
  'a',
  'an',
  'and',
  'are',
  'as',
  'at',
  'be',
  'but',
  'by',
  'can',
  'do',
  'does',
  'for',
  'from',
  'how',
  'i',
  'if',
  'in',
  'is',
  'it',
  'me',
  'my',
  'of',
  'on',
  'or',
  'our',
  'so',
  'that',
  'the',
  'their',
  'them',
  'then',
  'there',
  'these',
  'they',
  'this',
  'to',
  'was',
  'we',
  'what',
  'when',
  'which',
  'who',
  'will',
  'with',
  'you',
  'your',
]);

/** Lowercase, accents removed, split on anything that is not a letter or digit. */
export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .split(/[^a-z0-9]+/)
    .filter((w) => w !== '');
}

/** The distinct, meaningful terms of a question, in first-seen order. */
export function queryTerms(question: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const word of normalizeWords(question)) {
    if (STOPWORDS.has(word)) continue;
    if (seen.has(word)) continue;
    seen.add(word);
    out.push(word);
  }
  return out;
}

/**
 * Does `term` occur in `words`? A term of four characters or more also matches
 * a word it prefixes, so "configure" finds "configured" and "automation" finds
 * "automations" without a stemmer and without matching "to" against "token".
 */
function occurrences(words: readonly string[], term: string): number {
  let n = 0;
  for (const word of words) {
    if (word === term || (term.length >= 4 && word.startsWith(term))) n += 1;
  }
  return n;
}

/**
 * Field weights. A heading is what the section is ABOUT, so it outranks the
 * page it lives on, which outranks a passing mention in the prose.
 */
const WEIGHT_HEADING = 6;
const WEIGHT_PAGE_TITLE = 4;
const WEIGHT_PAGE_PATH = 3;
const WEIGHT_BODY = 2;
/** Repeats count, but with sharply diminishing returns — never as a new field. */
const WEIGHT_BODY_REPEAT = 0.2;
const BODY_REPEAT_CAP = 1;
/**
 * Coverage — the share of the question's terms a section addresses at all —
 * SCALES the field score instead of being added to it.
 *
 * It used to be a bonus of at most 3 points, and Reviewer C showed that was no
 * rule at all: a heading match is worth 6, so on a two-word question a section
 * answering half of it in its heading beat a section answering all of it in its
 * prose, and the bonus only decided a band so narrow that the test pinning it
 * had to repeat a word six times to land inside it. Proportional, the rule is
 * the one the ranking wants: answering half the question is worth about half as
 * much, whichever field the half was found in.
 *
 * The floor keeps a partial match from collapsing: a long question about one
 * topic still points at that topic. With two terms, matching one scales to 0.6
 * rather than 0.5.
 */
const COVERAGE_FLOOR = 0.2;

// ─── Release notes (#452) ─────────────────────────────────────────────────────

/** Words that make a question one about releases, accents already removed. */
const RELEASE_WORDS = new Set([
  'changelog',
  'release',
  'releases',
  'released',
  'version',
  'versions',
  'nouveaute',
  'nouveautes',
]);

/** `0.9.2`, `v0.9.2`, `0.9`: the version a question names, normalised to `0.9.2` / `0.9`. */
function versionIn(text: string): string | null {
  const m = /(?:^|[^\d.])v?(\d+\.\d+(?:\.\d+)?)(?![\d.]*\d)/i.exec(text);
  return m?.[1] ?? null;
}

/** A question that names Nodal itself, or "my / this version". */
const NAMES_NODAL = /\bnodal(?:-agents)?\b|\b(?:my|this) version\b|\b(?:ma|cette) version\b/i;

/**
 * Words that may stand right before a version number without tying it to
 * another product: grammar, release vocabulary, Nodal's own name. Any other
 * word there names what the number belongs to — "Node v22.0", "OAuth version
 * 2.0", "temperature 0.7" (Codex review of #452, pass 2).
 */
const LINK_WORDS = new Set([
  ...STOPWORDS,
  ...RELEASE_WORDS,
  'nodal',
  'agents',
  'notes',
  'changed',
  'new',
  'since',
  'between',
  'de',
  'la',
  'le',
  'les',
  'du',
  'des',
  'en',
  'depuis',
  'dans',
  'entre',
  'et',
  'ma',
  'cette',
]);

/**
 * The version a question names, and whether something ties it to ANOTHER
 * product: a word attached by a hyphen ("GPT-5.2"), or a product word right
 * before it, skipping a `v` and the word "version".
 */
function versionMentions(
  question: string,
): Array<{ version: string; foreign: boolean; prefixedV: boolean }> {
  const out: Array<{ version: string; foreign: boolean; prefixedV: boolean }> = [];
  const re = /(?:^|[^\d.])v?(\d+\.\d+(?:\.\d+)?)(?![\d.]*\d)/gi;
  for (let m = re.exec(question); m !== null; m = re.exec(question)) {
    const version = m[1]!;
    const numberAt = m.index + m[0].indexOf(version);
    const rawBefore = question.slice(0, numberAt);
    // A `v` glued to the number, as a word of its own: "v1.0.0", not "dev1.0".
    const prefixedV = /(?:^|[^a-z0-9])v$/i.test(rawBefore);
    const before = prefixedV ? rawBefore.slice(0, -1) : rawBefore;
    if (/[a-z0-9]-$/i.test(before)) {
      out.push({ version, foreign: true, prefixedV });
      continue;
    }
    const words = normalizeWords(before);
    while (words.length > 0 && /^versions?$/.test(words[words.length - 1]!)) words.pop();
    const last = words[words.length - 1];
    out.push({ version, foreign: last !== undefined && !LINK_WORDS.has(last), prefixedV });
  }
  return out;
}

/**
 * Does the release named in `heading` answer a question about `asked`? Equal
 * versions do, and a two-part version covers every release of that series:
 * "0.9" is answered by 0.9.0, 0.9.1, 0.9.2 (Codex review of #452, pass 3).
 */
export function versionCovers(asked: string, heading: string | null): boolean {
  if (heading === null) return false;
  if (asked === heading) return true;
  return asked.split('.').length === 2 && heading.startsWith(`${asked}.`);
}

/**
 * Is this a question about NODAL's releases, and which version does it name?
 *
 * A number another product owns is never Nodal's: a product word right before
 * it, or a hyphen ("Node v22.0", "OAuth version 2.0", "GPT-5.2"). Otherwise it
 * is, when the question names the product ("Nodal", "my version"), carries a
 * release word (version, release, changelog, what's new, what changed,
 * nouveautés) or glues a `v` to the number — whatever the number's form. Only
 * a bare number is judged by its form: two or three parts on the latest
 * release's major ("temperature 0.7" is excluded by its product word, not its
 * form). Without a number, the release words decide.
 */
export function nodalReleaseIntent(
  question: string,
  latestMajor: string | null,
): { asks: boolean; versions: string[] } {
  const namesNodal = NAMES_NODAL.test(question);
  const worded =
    /what'?s new|what (?:has )?changed/i.test(question) ||
    normalizeWords(question).some((w) => RELEASE_WORDS.has(w));
  const mentions = versionMentions(question);
  // EVERY version the question cites (Codex review of #452, pass 4): "between
  // versions 0.8 and 0.9" asks about two series, not the first one.
  const versions = mentions
    .filter((m) => {
      // A number another product owns is never ours ("Node v22.0", "OAuth
      // version 2.0", "GPT-5.2"), whatever words surround it.
      if (m.foreign) return false;
      // A version word, a glued `v` or the product's name is enough, whatever
      // the number's form. The form decides only for a bare number: Nodal's
      // published shape, two or three parts on the latest release's major.
      const shaped =
        /^\d+\.\d+(?:\.\d+)?$/.test(m.version) && m.version.split('.')[0] === latestMajor;
      return namesNodal || worded || m.prefixedV || shaped;
    })
    .map((m) => m.version)
    .filter((v, k, all) => all.indexOf(v) === k);
  const foreignOnly = mentions.length > 0 && mentions.every((m) => m.foreign);
  return {
    asks: namesNodal || versions.length > 0 || (worded && !foreignOnly),
    versions,
  };
}

function headingVersion(entry: Indexed): string | null {
  return versionIn(entry.section.heading);
}

/**
 * A release section whose heading carries the very version asked about is the
 * answer, whatever else the question says: it outranks any word match.
 */
const WEIGHT_NAMED_VERSION = 100;

export interface DocsHit extends DocsSection {
  score: number;
}

/**
 * A section's fields, split into words once.
 *
 * Built per INDEX, not per search: the words of a section never change, and an
 * agent asks the manual more than once in a job. Doing it inside the search
 * loop re-split every section's prose on every question (Reviewer C, pass 2,
 * P2-10) — the only part of the cost that grew with use.
 */
interface Indexed {
  section: DocsSection;
  heading: string[];
  pageTitle: string[];
  pagePath: string[];
  body: string[];
}

function indexSection(section: DocsSection): Indexed {
  return {
    section,
    heading: normalizeWords(section.heading),
    pageTitle: normalizeWords(section.pageTitle),
    pagePath: normalizeWords(section.page),
    body: normalizeWords(section.text),
  };
}

/**
 * The split words of an index, memoised on the index object itself.
 *
 * Keyed by identity rather than stored in a module variable so a test that
 * passes a literal index gets the same treatment as the shipped one, and two
 * different indexes never see each other's words. A WeakMap so a discarded
 * index is collected with its words.
 *
 * The contract that follows from keying on identity, and that Reviewer C asked
 * to see written down (pass 3, C1): an index is IMMUTABLE once searched.
 * Pushing a section onto `index.sections` after a first search does not
 * invalidate anything, and the second search answers out of the old
 * vocabulary. That is sound for the only index this ships with, which is read
 * once from a file that cannot change under a running process; a caller
 * building one by hand must pass a new object rather than edit the old one.
 */
const indexedCache = new WeakMap<DocsIndex, Indexed[]>();

function indexedSections(index: DocsIndex): Indexed[] {
  const hit = indexedCache.get(index);
  if (hit !== undefined) return hit;
  const built = index.sections.map(indexSection);
  indexedCache.set(index, built);
  return built;
}

function scoreSection(entry: Indexed, terms: readonly string[]): number {
  let score = 0;
  let matched = 0;
  for (const term of terms) {
    let hit = false;
    if (occurrences(entry.heading, term) > 0) {
      score += WEIGHT_HEADING;
      hit = true;
    }
    if (occurrences(entry.pageTitle, term) > 0) {
      score += WEIGHT_PAGE_TITLE;
      hit = true;
    }
    if (occurrences(entry.pagePath, term) > 0) {
      score += WEIGHT_PAGE_PATH;
      hit = true;
    }
    const inBody = occurrences(entry.body, term);
    if (inBody > 0) {
      score += WEIGHT_BODY + Math.min((inBody - 1) * WEIGHT_BODY_REPEAT, BODY_REPEAT_CAP);
      hit = true;
    }
    if (hit) matched += 1;
  }
  if (matched === 0) return 0;
  const coverage = matched / terms.length;
  return score * (COVERAGE_FLOOR + (1 - COVERAGE_FLOOR) * coverage);
}

/**
 * The best sections for a question, best first.
 *
 * `index` must be IMMUTABLE once passed here: its words are split once and
 * memoised against the object (see `indexedSections`).
 *
 * Ties break on the URL, so the result never depends on the order the index
 * happened to be written in. A question whose every word is a stopword, or
 * which matches nothing, returns an empty array — the caller says so rather
 * than inventing a page (invariant #4).
 */
export function searchDocs(index: DocsIndex, question: string, limit: number): DocsHit[] {
  const terms = queryTerms(question);
  if (terms.length === 0) return [];

  // Release notes answer "what changed", never "how do I" (#452): a long
  // release section repeats every product noun and would outrank the guide.
  // So they are eligible only for a question about releases, and a question
  // naming a version puts that version's section first.

  // A version the question names but the release notes do not carry is SAID,
  // with the latest one documented (Codex review of #452, P1): serving its
  // neighbours — "0.9.99" answered by v0.9.0, v0.9.1, v0.9.2 — reads as the
  // answer and is not one.
  const indexed = indexedSections(index);
  const releaseEntries = indexed.filter((e) => e.section.release === true);
  // Newest first: the release notes keep CHANGELOG.md's order.
  const latestMajor = releaseEntries[0]
    ? (headingVersion(releaseEntries[0])?.split('.')[0] ?? null)
    : null;
  const { asks: releases, versions } = nodalReleaseIntent(question, latestMajor);
  const covered = (v: string): boolean =>
    releaseEntries.some((e) => versionCovers(v, headingVersion(e)));
  const known = releases ? versions.filter(covered) : [];
  const missing = releases ? versions.filter((v) => !covered(v)) : [];
  // Release sections are served for a question about releases, unless every
  // version it names is missing: then only the notice(s) speak, never the
  // neighbours of an absent version.
  const releaseEligible = releases && (versions.length === 0 || known.length > 0);

  const scored: DocsHit[] = [];
  for (const entry of indexed) {
    if (entry.section.release === true && !releaseEligible) continue;
    let score = scoreSection(entry, terms);
    if (
      entry.section.release === true &&
      known.some((v) => versionCovers(v, headingVersion(entry)))
    ) {
      score += WEIGHT_NAMED_VERSION;
    }
    if (score > 0) scored.push({ ...entry.section, score });
  }
  scored.sort((a, b) => (b.score !== a.score ? b.score - a.score : a.url.localeCompare(b.url)));

  // Newest first: the release notes keep CHANGELOG.md's order.
  const latest = releaseEntries[0]?.section;
  const notices: DocsHit[] = latest
    ? missing.map((v) => ({
        page: latest.page,
        pageTitle: latest.pageTitle,
        heading: `No release notes for ${v}`,
        url: latest.url,
        text:
          `The release notes have no entry for version ${v}. ` +
          `The latest documented release is ${latest.heading}.`,
        release: true,
        score: Number.POSITIVE_INFINITY,
      }))
    : [];

  // The limit is SHARED between the series the question names: the best
  // section of each named series first, so "0.8 and 0.9" never loses 0.9 to
  // three 0.8.x sections (Codex review of #452, pass 4). Then the rest, by
  // score.
  const picked: DocsHit[] = [...notices];
  for (const v of known) {
    const best = scored.find(
      (h) => h.release === true && versionCovers(v, versionIn(h.heading)) && !picked.includes(h),
    );
    if (best) picked.push(best);
  }
  for (const h of scored) if (!picked.includes(h)) picked.push(h);
  return picked.slice(0, limit);
}
