// docs-index.ts — the shipped documentation, loaded from disk and searched
// lexically. Backs the `nodal_docs` built-in tool.
//
// WHY LEXICAL, OFFLINE, NO MODEL. The agent asking "where do I set up a
// Telegram bot?" is already inside an LLM turn; spending a second model call —
// or an embedding index that has to be built, stored and kept in sync — to
// find a page buys nothing a keyword match cannot. It also means this works on
// an install with no network and no API budget left, which is exactly the
// moment someone needs the documentation. Deterministic scoring keeps the
// tests honest: the same question always returns the same sections.
//
// The index itself is DERIVED from apps/docs/content/docs by
// apps/docs/scripts/gen-docs-index.ts. Nothing about the platform is written
// twice.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface DocsSection {
  page: string;
  pageTitle: string;
  heading: string;
  url: string;
  text: string;
}

export interface DocsIndex {
  generator: string;
  sections: DocsSection[];
}

// ─── Loading ──────────────────────────────────────────────────────────────────

/** Thrown when the index is missing or unreadable. Loud, never a silent empty. */
export class DocsIndexUnavailableError extends Error {
  constructor(probed: string[], cause?: unknown) {
    super(
      `nodal_docs: the documentation index was not found. Probed: ${probed.join(', ')}. ` +
        `It is generated by apps/docs/scripts/gen-docs-index.ts (run \`pnpm build\`) and ` +
        `shipped in the package next to migrations/.` +
        (cause instanceof Error ? ` Cause: ${cause.message}` : ''),
    );
    this.name = 'DocsIndexUnavailableError';
  }
}

/**
 * Where the index can be, in probe order — the same two layouts
 * `packages/db/src/migrate.ts` handles for `migrations/`:
 *   - bundled pack: this module is inlined into runner.js at the pack root, so
 *     the index is a SIBLING (`pack/docs-index.json`);
 *   - monorepo dev: this file is packages/tools/src/builtin/docs-index.ts, so
 *     the index is two levels up (`packages/tools/docs-index.json`).
 * Sibling first: cheaper, and the common case in a shipped artifact.
 */
export function docsIndexCandidatePaths(here: string): string[] {
  return [join(here, 'docs-index.json'), join(here, '..', '..', 'docs-index.json')];
}

let cached: DocsIndex | null = null;

/**
 * Read the index, once per process. Cached because it is a few hundred kB of
 * immutable data read on a tool call inside an LLM turn.
 */
export function loadDocsIndex(): DocsIndex {
  if (cached !== null) return cached;
  const here = dirname(fileURLToPath(import.meta.url));
  const probed = docsIndexCandidatePaths(here);
  const found = probed.find((p) => existsSync(p));
  if (found === undefined) throw new DocsIndexUnavailableError(probed);
  try {
    const parsed = JSON.parse(readFileSync(found, 'utf8')) as DocsIndex;
    if (!Array.isArray(parsed.sections)) throw new Error('no `sections` array');
    cached = parsed;
    return parsed;
  } catch (err) {
    throw new DocsIndexUnavailableError([found], err);
  }
}

/** Test seam: drop the cached index so a test can load a fixture. */
export function resetDocsIndexCache(): void {
  cached = null;
}

// ─── Scoring ──────────────────────────────────────────────────────────────────

/**
 * Words carried by every question, which would otherwise match every section
 * and flatten the ranking. Deliberately short: anything domain-bearing stays,
 * including "set" and "up", because "set up" IS the heading people are looking
 * for.
 */
const STOPWORDS = new Set([
  'a',
  'an',
  'and',
  'are',
  'as',
  'at',
  'be',
  'but',
  'by',
  'can',
  'do',
  'does',
  'for',
  'from',
  'how',
  'i',
  'if',
  'in',
  'is',
  'it',
  'me',
  'my',
  'of',
  'on',
  'or',
  'our',
  'so',
  'that',
  'the',
  'their',
  'them',
  'then',
  'there',
  'these',
  'they',
  'this',
  'to',
  'was',
  'we',
  'what',
  'when',
  'which',
  'who',
  'will',
  'with',
  'you',
  'your',
]);

/** Lowercase, accents removed, split on anything that is not a letter or digit. */
export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .split(/[^a-z0-9]+/)
    .filter((w) => w !== '');
}

/** The distinct, meaningful terms of a question, in first-seen order. */
export function queryTerms(question: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const word of normalizeWords(question)) {
    if (STOPWORDS.has(word)) continue;
    if (seen.has(word)) continue;
    seen.add(word);
    out.push(word);
  }
  return out;
}

/**
 * Does `term` occur in `words`? A term of four characters or more also matches
 * a word it prefixes, so "configure" finds "configured" and "automation" finds
 * "automations" without a stemmer and without matching "to" against "token".
 */
function occurrences(words: readonly string[], term: string): number {
  let n = 0;
  for (const word of words) {
    if (word === term || (term.length >= 4 && word.startsWith(term))) n += 1;
  }
  return n;
}

/**
 * Field weights. A heading is what the section is ABOUT, so it outranks the
 * page it lives on, which outranks a passing mention in the prose.
 */
const WEIGHT_HEADING = 6;
const WEIGHT_PAGE_TITLE = 4;
const WEIGHT_PAGE_PATH = 3;
const WEIGHT_BODY = 2;
/** Repeats count, but with sharply diminishing returns — never as a new field. */
const WEIGHT_BODY_REPEAT = 0.2;
const BODY_REPEAT_CAP = 1;
/** Matching MORE of the question beats matching one of its words loudly. */
const WEIGHT_COVERAGE = 3;

export interface DocsHit extends DocsSection {
  score: number;
}

/** A section's fields, pre-normalized. Built once per search, not per term. */
interface Indexed {
  section: DocsSection;
  heading: string[];
  pageTitle: string[];
  pagePath: string[];
  body: string[];
}

function indexSection(section: DocsSection): Indexed {
  return {
    section,
    heading: normalizeWords(section.heading),
    pageTitle: normalizeWords(section.pageTitle),
    pagePath: normalizeWords(section.page),
    body: normalizeWords(section.text),
  };
}

function scoreSection(entry: Indexed, terms: readonly string[]): number {
  let score = 0;
  let matched = 0;
  for (const term of terms) {
    let hit = false;
    if (occurrences(entry.heading, term) > 0) {
      score += WEIGHT_HEADING;
      hit = true;
    }
    if (occurrences(entry.pageTitle, term) > 0) {
      score += WEIGHT_PAGE_TITLE;
      hit = true;
    }
    if (occurrences(entry.pagePath, term) > 0) {
      score += WEIGHT_PAGE_PATH;
      hit = true;
    }
    const inBody = occurrences(entry.body, term);
    if (inBody > 0) {
      score += WEIGHT_BODY + Math.min((inBody - 1) * WEIGHT_BODY_REPEAT, BODY_REPEAT_CAP);
      hit = true;
    }
    if (hit) matched += 1;
  }
  if (matched === 0) return 0;
  return score + (matched / terms.length) * WEIGHT_COVERAGE;
}

/**
 * The best sections for a question, best first.
 *
 * Ties break on the URL, so the result never depends on the order the index
 * happened to be written in. A question whose every word is a stopword, or
 * which matches nothing, returns an empty array — the caller says so rather
 * than inventing a page (invariant #4).
 */
export function searchDocs(index: DocsIndex, question: string, limit: number): DocsHit[] {
  const terms = queryTerms(question);
  if (terms.length === 0) return [];

  const scored: DocsHit[] = [];
  for (const section of index.sections) {
    const score = scoreSection(indexSection(section), terms);
    if (score > 0) scored.push({ ...section, score });
  }

  scored.sort((a, b) => (b.score !== a.score ? b.score - a.score : a.url.localeCompare(b.url)));
  return scored.slice(0, limit);
}
