// pg-logging.test.ts — the embedded Postgres keeps a log of its own (issue #111).
//
// Twice on 2026-09-15 the runner logged `57P02: terminating connection because
// of crash of another server process`, the stack came down, and nothing on disk
// said which backend died or why. The cluster ran with no `logging_collector`,
// `pg-data/` had no `log/`, `~/.nodalai/logs/` had no postgres file.
//
// What these cases pin down is the CONFIGURATION that makes the crash lines
// exist. That a real postmaster then writes them is a different fact, proven by
// `postgres-logging.pg.test.ts` against a real cluster.

import { describe, it, expect, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  applyPostgresLoggingConfig,
  mergeAutoConf,
  postgresLoggingSettings,
  quoteGuc,
} from '../lib/pg-logging.ts';

const dirs: string[] = [];
function tempDir(): string {
  const d = mkdtempSync(join(tmpdir(), 'nodal-pglog-'));
  dirs.push(d);
  return d;
}

afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

describe('postgresLoggingSettings @cap:installer-et-demarrer/moteur', () => {
  it('turns the collector on and points it outside the data dir', () => {
    const s = postgresLoggingSettings('C:/Users/x/.nodalai/logs/postgres');
    expect(s['logging_collector']).toBe('on');
    expect(s['log_directory']).toBe('C:/Users/x/.nodalai/logs/postgres');
  });

  it('writes Windows paths with forward slashes', () => {
    // A GUC string is not a C string, so a backslash usually survives — but
    // "usually" is not a property worth depending on when the alternative costs
    // one replace. Forward slashes are accepted on every platform.
    const s = postgresLoggingSettings('C:\\Users\\x\\.nodalai\\logs\\postgres');
    expect(s['log_directory']).toBe('C:/Users/x/.nodalai/logs/postgres');
  });

  it('carries the pid and a millisecond timestamp in every line', () => {
    // These two are the whole diagnosis: attributing a crash means matching a
    // pid against what a process table said at a given instant.
    const prefix = postgresLoggingSettings('/tmp/x')['log_line_prefix'] ?? '';
    expect(prefix).toContain('%p');
    expect(prefix).toContain('%m');
  });

  it('keeps the LOG level, which is where the signal number is written', () => {
    // `log_min_messages = warning` reads like it would drop a LOG line, and it
    // does not: for this setting the ranking puts LOG ABOVE error
    // (… WARNING < ERROR < LOG < FATAL < PANIC), precisely so that
    // server-lifecycle messages survive a restrictive value. "server process
    // (PID n) was terminated by signal 9" is a LOG line, and it is the one this
    // whole file exists to preserve.
    expect(postgresLoggingSettings('/tmp/x')['log_min_messages']).toBe('warning');
  });

  it('rotates by age and by size, and does not keep every day forever', () => {
    const s = postgresLoggingSettings('/tmp/x');
    expect(s['log_rotation_age']).toBe('1d');
    expect(s['log_rotation_size']).toMatch(/^\d+kB$/);
    expect(s['log_truncate_on_rotation']).toBe('on');
  });
});

describe('quoteGuc @cap:installer-et-demarrer/moteur', () => {
  it('doubles an inner quote instead of escaping it', () => {
    // A backslash escape is what a JS author reaches for and it is wrong here:
    // postgresql.conf doubles the quote. Getting this wrong truncates the
    // value, which for log_directory means logging into the wrong place.
    expect(quoteGuc("it's")).toBe("'it''s'");
  });
});

describe('mergeAutoConf @cap:installer-et-demarrer/moteur', () => {
  it('replaces our own keys rather than appending a second copy', () => {
    const out = mergeAutoConf(
      "logging_collector = 'off'\nlog_directory = 'somewhere/else'\n",
      postgresLoggingSettings('/tmp/logs'),
    );
    expect(out.match(/^logging_collector = /gm)).toHaveLength(1);
    expect(out).toContain("logging_collector = 'on'");
    expect(out).not.toContain('somewhere/else');
  });

  it('keeps a setting somebody else put there with ALTER SYSTEM', () => {
    // Nothing in this product runs ALTER SYSTEM. A user with a psql prompt can,
    // and silently discarding their setting would be the kind of surprise this
    // repository keeps apologising for.
    const out = mergeAutoConf("shared_buffers = '256MB'\n", postgresLoggingSettings('/tmp/logs'));
    expect(out).toContain("shared_buffers = '256MB'");
  });

  it('drops comments and blank lines rather than duplicating the header', () => {
    const out = mergeAutoConf(
      "# Do not edit this file manually!\n\nwork_mem = '4MB'\n",
      postgresLoggingSettings('/tmp/logs'),
    );
    expect(out.match(/^# Do not edit this file manually!$/gm)).toHaveLength(1);
    expect(out).toContain("work_mem = '4MB'");
  });
});

describe('applyPostgresLoggingConfig @cap:installer-et-demarrer/moteur', () => {
  it('writes postgresql.auto.conf and creates the log directory', () => {
    const dataDir = tempDir();
    const logDir = join(tempDir(), 'logs', 'postgres');
    applyPostgresLoggingConfig(dataDir, logDir);
    expect(existsSync(logDir)).toBe(true);
    const written = readFileSync(join(dataDir, 'postgresql.auto.conf'), 'utf-8');
    expect(written).toContain("logging_collector = 'on'");
    expect(written).toContain(logDir.replace(/\\/g, '/'));
  });

  it('is idempotent across restarts — it runs on EVERY start, not once at initdb', () => {
    // A data directory created by an older version has none of this, and a user
    // who cleared the file gets it back. Running twice must not accumulate.
    const dataDir = tempDir();
    const logDir = join(tempDir(), 'logs');
    applyPostgresLoggingConfig(dataDir, logDir);
    const first = readFileSync(join(dataDir, 'postgresql.auto.conf'), 'utf-8');
    applyPostgresLoggingConfig(dataDir, logDir);
    expect(readFileSync(join(dataDir, 'postgresql.auto.conf'), 'utf-8')).toBe(first);
  });

  it('replaces an unreadable existing file rather than refusing to boot', () => {
    const dataDir = tempDir();
    const logDir = join(tempDir(), 'logs');
    writeFileSync(join(dataDir, 'postgresql.auto.conf'), Buffer.from([0xff, 0xfe, 0x00]));
    expect(() => applyPostgresLoggingConfig(dataDir, logDir)).not.toThrow();
    expect(readFileSync(join(dataDir, 'postgresql.auto.conf'), 'utf-8')).toContain(
      "logging_collector = 'on'",
    );
  });
});
